name:                aoc2018
version:             0.1.0.0
github:              "2mol/aoc2018"
license:             BSD3
author:              "Juri Chomé"
maintainer:          "juri.chome@gmail.com"
copyright:           "2019 Juri Chomé"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

executables:
  aoc2018:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

